### ISSUE TITLE
Wrong permissions ownership of installed binaries

### ISSUE THREAD

**Issue by stroeder** [ltb-project/openldap-deb#10]
slapd executable, all libs, all slapd modules, etc. are installed with ownership ldap:ldap. But ldap is the demon user for running slapd. This is very bad security practice.

Only the database directory /usr/local/openldap/var/openldap-data must have ownership ldap:ldap. The rest of all files should be installed with ownership root:root (with same permissions like now).

**Comment by davidcoutadeur** [comment]
You must also add /usr/local/openldap/var/run to ldap:ldap user, else OpenLDAP will not start

**Comment by coudot** [comment]
Seems we also need to let OpenLDAP user read/write configuration files:
```
[root@centos7 ~]# /usr/local/openldap/sbin/slapd-cli debug
slapd-cli: [INFO] Using /usr/local/openldap/etc/openldap/slapd-cli.conf for configuration
slapd-cli: [INFO] Halting OpenLDAP...
slapd-cli: [INFO] Can't read PID file, to stop OpenLDAP try: /usr/local/openldap/sbin/slapd-cli forcestop
slapd-cli: [INFO] No db_recover done
slapd-cli: [INFO] Launching OpenLDAP...
slapd-cli: [OK] File descriptor limit set to 1024
5ac24989 @(#) $OpenLDAP: slapd 2.4.46 (Apr  2 2018 17:02:51) $
        clement@centos7:/home/clement/build/BUILD/openldap-2.4.46/servers/slapd
5ac24989 could not open config file "/usr/local/openldap/etc/openldap/slapd.conf": Permission denied (13)
```

Maybe this works in Debian packaging if slapd.conf file has 644 rights. But by default slapd.conf should be 600 (no access from other system users).

**Comment by davidcoutadeur** [comment]
Indeed, in Debian, permissions are 644 for slapd.conf, and should be 600.
Contrary to similar daemons (apache for example), OpenLDAP is loading its slapd.conf configuration file with daemon user/group rights...
So these files should have ldap:ldap owner:
- ppm.conf,
- chek_password config file,
- slapd.conf.

**Comment by stroeder** [comment]
Clément OUDOT wrote:
> Seems we also need to let OpenLDAP user read/write configuration files:

Static config file has to be readable but should *not* be writeable by
the demon.

Dynamic config directory has to be writeable by the demon.

> clement@centos7:/home/clement/build/BUILD/openldap-2.4.46/servers/slapd
> 5ac24989 could not open config file
> "/usr/local/openldap/etc/openldap/slapd.conf": Permission denied (13) |
> 
> Maybe this works in Debian packaging if slapd.conf file has 644 rights.
> But by default slapd.conf should be 600 (no access from other system users).

Correct ownership/permission for static config file:

chown root:ldap /usr/local/openldap/etc/openldap/slapd.conf
chmod 640 /usr/local/openldap/etc/openldap/slapd.conf

Correct ownership/permission for dynamic config directory:

chown -R root:ldap /usr/local/openldap/etc/openldap/slapd.d
chmod 770 /usr/local/openldap/etc/openldap/slapd.d

**Comment by coudot** [comment]
Ok, for the moment we don't create a slapd.d directory, I will fix rights for other files in RPM packaging

**Comment by davidcoutadeur** [comment]
Thank you Michael for your answer.
I don't see the point to set user owner to root.
We could do:
```
chown ldap:ldap /usr/local/openldap/etc/openldap/slapd.conf
chmod 440 /usr/local/openldap/etc/openldap/slapd.conf
```
However, it will be painfull when editing file as root, as it will always ask for confirmation to write file.

We do not use the slapd.d directory at installation, so it is up to the administrator to manage it accordingly.

**Comment by coudot** [comment]
@davidcoutadeur I understand @stroeder proposition, as only root user should be able to modify the slapd.conf file, and ldap user should only be able to read it.

**Comment by davidcoutadeur** [comment]
Ok, why not...

**Comment by stroeder** [comment]
davidcoutadeur wrote:
> Thank you Michael for your answer.
> I don't see the point to set user owner to root.

root should be able to read and write the file.
ldap should be able to read the file but not write it.

Please get this right.

> However, it will be painfull when editing file as root, as it will
> always ask for confirmation to write file.

Who or which component will ask for confirmation?
Are you talking about debconf?

The LTB packages are not really Debian compliant anyway [1] because
AFAIK on Debian you must not mark files beneath /usr/local as config
files. This also might be the real problem.

[1] One of my customer builds own LTB-forked packages with mini-buildd
and it's a PITA.

**Comment by coudot** [comment]
@stroeder yes, we are not building packages with all Debian requirements because it will not be an official package

I made the changes for RPM : https://github.com/ltb-project/openldap-rpm/commit/a0ad91213e308a62bad1e842e92e7a72d6240503

**Comment by davidcoutadeur** [comment]
> Who or which component will ask for confirmation?
> Are you talking about debconf?

For example, when editing the slapd.conf file with vi, when logged as root.

> The LTB packages are not really Debian compliant anyway [1] because AFAIK on Debian you must not mark files beneath /usr/local as config files. This also might be the real problem. [1] One of my customer builds own LTB-forked packages with mini-buildd and it's a PITA.

What is mini-build and what is PITA ?

**Comment by stroeder** [comment]
davidcoutadeur wrote:
>     Who or which component will ask for confirmation?
>     Are you talking about debconf?
> 
> For example, when editing the slapd.conf file with vi, when logged as root.

This should not be a problem at all.

> What is mini-build and what is PITA ?

http://mini-buildd.installiert.net/

Building the LTB packages with mini-buildd did not really work correctly
even when switching off most compliance checks.

The issue with not marking config files as such is that config file
might get overwritten by a package upgrade.

**Comment by davidcoutadeur** [comment]
config files are marked as such, as far as I know. (see openldap-ltb-2.4.46/debian/openldap-ltb-check-password.conffiles, openldap-ltb-2.4.46/debian/openldap-ltb.conffiles, openldap-ltb-2.4.46/debian/openldap-ltb-ppm.conffiles)
@stroeder: I would be happy to improve these problems if you point what is wrong?

**Comment by konqui15** [comment]
@davidcoutadeur 
You are right, you use configfiles, but the config files are located in `/usr/local`. If you build your own packages and use debian lintian check (it is part of you build system here: mini-buildd), you will get an error and can not overwrite this (file-in-usr-marked-as-conffile). The only quick solution I found, do not flag this files as configfiles.

here a list of what you have to overwrite:
* helper-templates-in-copyright
* dir-in-usr-local
* file-in-usr-local
* postrm-does-not-call-updaterc.d-for-init.d-script
* prerm-calls-updaterc.d
* non-empty-dependency_libs-in-la-file

**Comment by davidcoutadeur** [comment]
@konqui15 ok, thank for your feedback.
Unfortunately, I do have to mark these files as config file, because when performing an upgrade, Debian have to consider them as configuration and don't overwrite.

**Comment by davidcoutadeur** [comment]
@stroeder @konqui15 @coudot 
Anyway, making OpenLDAP deb package conform to lintian is not an easy task and I propose to make it as a next LTB release target.
I am creating a new issue on which I will work later, and encourage you to comment if possible.
