### ISSUE TITLE
After installing, LDAP database is empty. How to populate it?

### ISSUE THREAD

**Issue by Oliveiras** [ltb-project/openldap-deb#100]
I followed the documentation, installed the packages and edited the `slapd-cli.conf` file. But I can't find how to create and populate the database with the declared entries.

Trying to follow other tutorials, they say to use the command `dpkg-reconfigure slapd` to create and populate the database. What would be the equivalent command for these package?

Also, this information seems to be missing in the docs. It says how to configure slapd-cli but not how to apply.

**Comment by davidcoutadeur** [comment]
Hi,

`dpkg-reconfigure slapd` is for debian packaging of OpenLDAP, it is different way to do for OpenLDAP-LTB packages.

You can read the documentation of `slapd-cli` tool here: https://ltb-project.org/documentation/slapd-cli.html

Especially, the target `importdatatemplate` is what you are looking for : it imports test data.

`importflatconfigtemplate` or `importldifconfigtemplate` let you import the configuration.

Before opening a ticket, please try sending a mail to the mailing list with your questions. If there is real bug or improvement, then open a ticket.
