### ISSUE TITLE
Support for Debian 12 (bookworm)

### ISSUE THREAD

**Issue by nxadm** [ltb-project/openldap-deb#103]
Debian 12 (bookwork) was released on 2023-06-10, while Debian 10 reached it end of life on 2022-09-10. See: https://wiki.debian.org/DebianReleases#Production_Releases .

Is it possible to add Debian 12 to the repos?

Thank you!

**Comment by davidcoutadeur** [comment]
Hello,

Yes, it is definitely in our plans to add debian 12 repos.

Not sure if we can release this very quickly, but we could take advantage of the next openldap release to add the repo as well.

**Comment by nxadm** [comment]
I am working on moving our OpenLDAP setup in containers (and using the opportunity to re-architecture), so for me 11 is fine. Ping if you need help, openldap-ltb has been rock-solid for years.

**Comment by davidcoutadeur** [comment]
Done in 2.5.15 / 2.6.5 releases
