### ISSUE TITLE
Provide packages for Debian 13/sid

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/openldap-deb#106]
It could be usefull to provide packages for Debian 13/sid, for testing new feature for example.

**Comment by simonelbaz** [comment]
Hi @davidcoutadeur ,

would it be possible to generate 2.5.16 packages for Debian 12 (bookworm) ?

I can help if needed.

Thanks

**Comment by davidcoutadeur** [comment]
Hello @simonelbaz , 2.5.16 packages are coming soon for debian 10, 11, 12 and 13
