### ISSUE TITLE
Make ldapi:/// working

### ISSUE THREAD

**Issue by babafou** [ltb-project/openldap-deb#119]
As the usual LDAPI URI (ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi) is long and ugly, it might be useful to have it in the /usr/local/openldap/etc/openldap/ldap.conf file:

URI     ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi

That way, no need to specify it on the command line.

**Comment by davidcoutadeur** [comment]
I am not fond of modifying ldap.conf, which should be customizable by the administrator.

But we could create a symbolic link :

```
ln -s /var/run/slapd/ldapi /usr/local/openldap/var/run/ldapi
```

**Comment by babafou** [comment]
Whatever works by default is fine.
