### ISSUE TITLE
How is the status about Debian packages for stretch?

### ISSUE THREAD

**Issue by MrRagga-** [ltb-project/openldap-deb#12]

**Comment by davidcoutadeur** [comment]
Hi,
Packages are available for Debian stretch on 64 bits systems. Just replace wheezy by stretch in the repository.

**Comment by davidcoutadeur** [comment]
@coudot : Maybe we could also provide the archive on https://ltb-project.org/download ?

**Comment by MrRagga-** [comment]
That would be very helpful, since this is exactly the page where I've been regular looking for the status ;)

**Comment by coudot** [comment]
Right, I need to update the wiki

**Comment by coudot** [comment]
Done
