### ISSUE TITLE
use new 2.3 openldap-initscript

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/openldap-deb#13]
use new 2.3 openldap-initscript:
https://github.com/ltb-project/openldap-initscript/issues/4

**Comment by coudot** [comment]
For information, I made a postscript in RPM packages that move /etc/default/slapd to /usr/local/openldap/etc/openldap/slapd-cli.conf (if /etc/default/slapd exists). It allows to keep service configuration when updating packages.

**Comment by davidcoutadeur** [comment]
Good idea, I will do the same...

**Comment by davidcoutadeur** [comment]
All these modifications need a new package generation.
Will do this on tomorrow, and send you the result.

**Comment by coudot** [comment]
Great, I think I will try to publish RPM package tonight, as all seems to work.
