### ISSUE TITLE
older debian packages are removed

### ISSUE THREAD

**Issue by fmartin-linagora** [ltb-project/openldap-deb#18]
Older Debian packages must always be kept please. :)

**Comment by coudot** [comment]
Debian repository manager (reprepro) always remove old packages when adding new versions

**Comment by fmartin-linagora** [comment]
:'( 
As you may already know, there are other solutions like https://www.aptly.info/ that could help if you have time ! :)

Thank you for your answer.

**Comment by davidcoutadeur** [comment]
Maybe could you give a look @coudot?
I also think it would be nice to keep all packages, so that any user could install the version he wants.
If you don't have time, tell me and I'll try to check the possible solutions.

**Comment by coudot** [comment]
I looked at aptly, seems indeed a good solution, but I need to recreate all repositories, and I will not have the time yet. I will publish 2.4.47 with reprepro and see then how to migrate to new repositories.

**Comment by coudot** [comment]
We now use aptly, new packages will be added without removing older ones.

**Comment by fmartin-linagora** [comment]
So nice. Thank you very much.
