### ISSUE TITLE
integrate explockout

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/openldap-deb#19]
integrate explockout
https://github.com/davidcoutadeur/explockout

**Comment by coudot** [comment]
Hello, I see that you created a separted package for explockout. In RPM, I let it inside contrib-overlays, we can discuss what is the best to do?

**Comment by davidcoutadeur** [comment]
I would have preferred explockout to be in official OpenLDAP contrib, but unfortunately it is not yet... I'll keep pushing this to the community.
Anyway I thought our contrib-overlays was reserved to official contrib overlays, so that's the main reason.

A consequence is that the install process is more like ppm or initscript than any overlay in contrib directory, so it makes more sense to me to make a different package.

What is your opinion about this?

**Comment by davidcoutadeur** [comment]
I would have preferred explockout to be in official OpenLDAP contrib, but unfortunately it is not yet... I'll keep pushing this to the community.
Anyway I thought our contrib-overlays was reserved to official contrib overlays, so that's the main reason.

A consequence is that the install process is more like ppm or initscript than any overlay in contrib directory, so it makes more sense to me to make a different package.

What is your opinion about this?

**Comment by coudot** [comment]
Ok, I am doing a separate package in RPM too so we have the same organization.

We can reopen the discussion when working on #21
