### ISSUE TITLE
Data corruption on data base mdb

### ISSUE THREAD

**Issue by MamounENGIE** [ltb-project/openldap-deb#27]
Hello, 
We installed the package OpenLDAP-ltb on ubuntu 16.04.2 and we have two LDAP data bases working in multi-master mode replication.
We then, imported our data with "slapadd" on each node. On the first node we have all our data which was imported before with "slapdaddd" and we have 9Go in mdb.data.
In the second node, we can't find all the data that was imported with "slapdadd" and still, we have the same size (9Go) in mdb.data.
We cannot explain why we can't find our data in the second node anymore...
Do you have any idea how is that possible ? And do you know if we can recover our data that was imported ?
Thank you in advance for your response and your help.

**Comment by davidcoutadeur** [comment]
Hi Mamoun,

I think in this case,
- either there should be grave errors in the OpenLDAP logs when 
replicating or importing the data,
- either there is a problem with the data visibility : permissions 
rights on the file system? OpenLDAP ACLs? index?

Anyway, it is much too early to imput the responsability of a data 
corruption to the OpenLDAP-LTB package...

Regards,

David

**Comment by coudot** [comment]
Could you check that the 9GB size is the real file size, and not the reserved size configured in olcMdbMaxsize?

**Comment by coudot** [comment]
When doing the slapadd command, is slapd stopped?

Which options are you using with slapadd command?

**Comment by MamounENGIE** [comment]
Hello, 

Yes, when using the slapadd command, slapd is stopped, the command used is : 

slapadd -l ${ldifFile} -F ${slapd.d directory} -c -d 512

**Comment by coudot** [comment]
First you could remove "-c" so you stop at first error. There should not be any error.

Then for a bulk import, it is better to use -q

**Comment by MamounENGIE** [comment]
Hello,
Thank you for your response.
What is the purpose of the option -q when doing bulk import?

**Comment by coudot** [comment]
From slapadd manpage:
```       -q     enable quick (fewer integrity checks) mode.  Does fewer consistency checks
              on the input data, and no consistency checks when writing the database.
              Improves the load time but if any errors or interruptions occur the resulting
              database will be unusable.
```

It allows a fast data import. We use it in our OpenLDAP init script for data restore

**Comment by MamounENGIE** [comment]
Thank you for your response.
Actually, we had the exact same logs file when we imported the data on both nodes. Errors in both nodes are the same. And the size of data-base (data.mdb) is the same, so i don't think we had a problem when importing data...

**Comment by coudot** [comment]
What is the error?

**Comment by MamounENGIE** [comment]
We resynchronized both nodes with backuping the data from the first node and restoring them in the second node and then we launch a global resynchronization with adding the option -c in the second node. 
Now we have the exact same entries in both nodes. 
Still, we have a little problem : 
When i launched the command **slapd-cli checksync** in ordre to check the replication and synchronization, I got an OK in the second node which is great but when i launched it the first node, I got a KO. Here is the result of the command in the first and the second node :

- **First node** : 
slapd-cli: [INFO] Using /usr/local/openldap/etc/openldap/slapd-cli.conf for configuration
slapd-cli: [INFO] Checking synchronization...
Checking host ldaps://AZDMPA002VM041.api.engie.fr:636
  Checking SID #001#
    ERROR: remote (20190129165545.239228Z#000000#001#000000) and local (20190129164600.230776Z#000000#001#000000) contextCSN found, but not synchronized!
  Checking SID #002#
    INFO: remote (20190129164601.166126Z#000000#002#000000) and local (20190129164601.166126Z#000000#002#000000) contextCSN found and synchronized
Checking host ldaps://AZDMPA002VM042.api.engie.fr:636
  Checking SID #001#
    ERROR: remote (20190129165545.239228Z#000000#001#000000) and local (20190129164600.230776Z#000000#001#000000) contextCSN found, but not synchronized!
  Checking SID #002#
    INFO: remote (20190129164601.166126Z#000000#002#000000) and local (20190129164601.166126Z#000000#002#000000) contextCSN found and synchronized
slapd-cli: [KO] Local directory not synchronized to one of its declared providers

- **Second node** : 

Checking host ldaps://AZDMPA002VM041.api.engie.fr:636
  Checking SID #001#
    INFO: remote (20190129164724.680859Z#000000#001#000000) and local (20190129164724.680859Z#000000#001#000000) contextCSN found and synchronized
  Checking SID #002#
    INFO: remote (20190129164601.166126Z#000000#002#000000) and local (20190129164601.166126Z#000000#002#000000) contextCSN found and synchronized
Checking host ldaps://AZDMPA002VM042.api.engie.fr:636
  Checking SID #001#
    INFO: remote (20190129164724.680859Z#000000#001#000000) and local (20190129164724.680859Z#000000#001#000000) contextCSN found and synchronized
  Checking SID #002#
    INFO: remote (20190129164601.166126Z#000000#002#000000) and local (20190129164601.166126Z#000000#002#000000) contextCSN found and synchronized
slapd-cli: [OK] Local directory synchronized to every declared provider


Thank you in advance for your response and your help.

**Comment by coudot** [comment]
Maybe the replication was not finished when checking node one? You can modify one entry on node one and then one entry on node two to force synchronization update.

**Comment by coudot** [comment]
Hello,

You can use mdb_stat to check to content of the mdb database. And also check that both nodes are NTP synced, as OpenLDAP replication is based on timestamps.

If you need professionnal support, check https://ltb-project.org/professionalservices. I personally works for [Worteks](https://www.worteks.com)

**Comment by mejdibennour** [comment]
Hello, here are the mdb_stat results : 

**node 1 :** 
$ sudo mdb_stat -e /data/openldap-ltb/var/openldap-data/
Environment Info
  Map address: (nil)
  Map size: 68719476736
  Page size: 4096
  Max pages: 16777216
  Number of pages used: 972738
  Last transaction ID: 3613191
  Max readers: 126
  Number of readers used: 7
Status of Main DB
  Tree depth: 1
  Branch pages: 0
  Leaf pages: 1
  Overflow pages: 0
  Entries: 10

**node 2 :** 
$ sudo mdb_stat -f /data/openldap-ltb/var/openldap-data/
Freelist Status
  Tree depth: 3
  Branch pages: 14
  Leaf pages: 2605
  Overflow pages: 0
  Entries: 92641
  Free pages: 967715
Status of Main DB
  Tree depth: 1
  Branch pages: 0
  Leaf pages: 1
  Overflow pages: 0
  Entries: 10

**Comment by coudot** [comment]
So you see that the number of pages used is not the same between the 2 nodes.

**Comment by mejdibennour** [comment]
Hello,
I have made a slapcat to count the number of entries in the db.
Here is the result : 
Node1 : 2739899
Node2 : 4483
Lokks like it is a db issue.

**Comment by coudot** [comment]
Indeed, there should be a difference between your two servers. Check OpenLDAP configurations, packages versions, disk space...

**Comment by davidcoutadeur** [comment]
There is no evidence that the LTB packaging is responsible for any of these errors.
I close the issue.
