### ISSUE TITLE
Failed to start slapd service when adding the option -d : Time-Out

### ISSUE THREAD

**Issue by MamounENGIE** [ltb-project/openldap-deb#28]
Hello, 
We installed openldap-ltb package, it was starting, restarting and stopping very well without any problem, but since we added the option "-d" to the **slapd-cli.conf** file in order to enable the debug we have some issues when starting the slapd service. It failed to start whith a time out message but then when we restart it again it restart with a success. 
Do you know why when adding -d option we have this time-out problem?
Thank you in advance for your response.

**Comment by coudot** [comment]
slapd-cli already has a debug mode, you don't need to add -d option.

Do: 
```
slapd-cli debug
```

See OpenLDAP init script documentation: https://ltb-project.org/documentation/openldap-initscript

**Comment by MamounENGIE** [comment]
Hello ! 
Thank you for very much for your answer. It is much better now.
