### ISSUE TITLE
issue with Debian Stretch postinst when attempting to build a Docker image

### ISSUE THREAD

**Issue by fred49** [ltb-project/openldap-deb#30]
Hi,
I'm trying to build a docker image using OpenLDAP LTB project and I have an issue with the postinst script.
It requires to have systemctl installed. I don't want to compile openldap, I want reuse Debian packages even if it is no perfect. So is it possible to test if systemctl exists and then call it ?

Fred.

**Comment by davidcoutadeur** [comment]
Hi,
The best way would be to call the slapd-cli script from postinst.
1. slapd-cli is always present
2. anyway, systemd script *is* calling slapd-cli, so it is more efficient to call slapd-cli directly.
-> TODO

**Comment by fmartin-linagora** [comment]
Hi,
sorry but you can't use your solution because you still have to enable your service.
Cf current lines of code :
```
systemctl enable slapd || exit $?
systemctl start slapd || exit $?
```

**Comment by davidcoutadeur** [comment]
Hi @fmartin-linagora 
The solution I propose:

if systemd available: keep the current behaviour
else: start process with slapd-cli, but don't set "start on boot"

**Comment by davidcoutadeur** [comment]
As discussed, the better for docker is not to start OpenLDAP.
So:

```
if systemd available: keep the current behaviour
else: do nothing (don't start on boot, don't start slapd-cli now)
```

**Comment by davidcoutadeur** [comment]
Also, another improvement is to check the presence of rsyslog before configuring the logs.

**Comment by davidcoutadeur** [comment]
Done in https://github.com/ltb-project/openldap-deb/releases/tag/v2.4.48

**Comment by davidcoutadeur** [comment]
Error reproduced installing with docker:
- `FROM debian:stable`
- packages: `openldap-ltb` `openldap-ltb-contrib-overlays` `openldap-ltb-mdb-utils` `openldap-ltb-ppm`
- the error incriminate directly systemctl

**Comment by davidcoutadeur** [comment]
New tests on docker + OpenLDAP 2.5 show no problem

See #71
