### ISSUE TITLE
Useless execution right is added to /lib/systemd/system/slapd.service

### ISSUE THREAD

**Issue by fmartin-linagora** [ltb-project/openldap-deb#33]
Hello,
During installation process, execution right is added to the /lib/systemd/system/slapd.service which is useless : 
```
 systemd[1]: Configuration file /lib/systemd/system/slapd.service is marked executable. Please remove executable permission bits. Proceeding anyway.
```
Fred.

**Comment by davidcoutadeur** [comment]
Done in https://github.com/ltb-project/openldap-deb/releases/tag/v2.4.48
