### ISSUE TITLE
Backup directory has not correct permissions

### ISSUE THREAD

**Issue by coudot** [ltb-project/openldap-deb#40]
When installing Debian packages and running `slapd-cli backup` we have an error because backup directory is not writable by ldap user.

**Comment by coudot** [comment]
Hello @davidcoutadeur I let you check my pull request and merge it if it is ok for you.

**Comment by davidcoutadeur** [comment]
@coudot Nice, you have time to create bugfixes during workshops ;)
Seems fine, merged.
