### ISSUE TITLE
 Release OpenLDAP 2.4.49

### ISSUE THREAD

**Issue by coudot** [ltb-project/openldap-deb#42]

**Comment by coudot** [comment]
@davidcoutadeur do you plan to release a new version of ppm before releasing 2.4.49?

**Comment by davidcoutadeur** [comment]
@coudot no, I won't. Each ppm issue is to be applied for OpenLDAP 2.5 release.

**Comment by coudot** [comment]
Ok, so we can release 2.4.49 packages with current ppm version. Il will work on RPM packages tomorrow.

**Comment by davidcoutadeur** [comment]
done
