### ISSUE TITLE
erroring during postinstall scripts after upgrade of openldap packages from LTB repo

### ISSUE THREAD

**Issue by bv-unibs** [ltb-project/openldap-deb#7]
Hi, 
we've experimenting some issues during the upgrade of openldap packages from LTB repository on our openldap server.

The openldap server is 2.4.44 and o.s. is a debian 8 

The errors regarding openldap are the following

Can you please help us?

regards

Installing new version of config file /etc/init.d/slapd ...
addgroup: The group `ldap' already exists as a system group. Exiting.
Job for slapd.service failed. See 'systemctl status slapd.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript slapd, action "start" failed.
dpkg: error processing package openldap-ltb (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of openldap-ltb-check-password:
 openldap-ltb-check-password depends on openldap-ltb; however:
  Package openldap-ltb is not configured yet.

dpkg: error processing package openldap-ltb-check-password (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Processing triggers for systemd (215-17+deb8u7) ...
Errors were encountered while processing:
 openldap-ltb
 openldap-ltb-check-password
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by davidcoutadeur** [comment]
Hi,
Could you tell me the result of the following commands please:
```
systemctl status slapd
journalctl -xn
systemctl start slapd
```

**Comment by bv-unibs** [comment]
Here's the results, but i need to explain that the slapd.service is disabled on our setup, cause we've configured the openldap service as: slapd-ldap-slave-unibs.service, as you can see in the last command here...

so the problem is slapd.service needs to be disabled cause we don't use it in our installation, the real openldap service is slapd-ldap-slave-unibs.service, that's up and running..

I think the problem here is the ltb package doesn't recognize the fact that the service is named differently from the standard and so cannot setup correctly the post-installation setup for openldap..

thank for your help..

systemctl status slapd
● slapd.service - LSB: OpenLDAP
   Loaded: loaded (/etc/init.d/slapd)
   Active: inactive (dead)

[root@ldap-slave:~]# journalctl -xn
-- Logs begin at Tue 2017-07-25 03:21:00 CEST, end at Tue 2017-07-25 08:34:17 CEST. --
Jul 25 08:34:16 ldap-slave slapd-ldap-slave-unibs[914]: conn=6231 op=776 SEARCH RESULT tag=101 err=0 nentries=1 text=
Jul 25 08:34:17 ldap-slave slapd-ldap-slave-unibs[914]: conn=3961 op=25097 SRCH base="ou=utenti,o=unibs,dc=unibs,dc=it" scope=2 deref=0 filter="(&(mail=*@student
Jul 25 08:34:17 ldap-slave slapd-ldap-slave-unibs[914]: conn=3961 op=25097 SRCH attr=radiusNASIpAddress radiusExpiration acctFlags userPassword dBCSPwd sambaNtPa
Jul 25 08:34:17 ldap-slave slapd-ldap-slave-unibs[914]: conn=3961 op=25097 SEARCH RESULT tag=101 err=0 nentries=1 text=
Jul 25 08:34:17 ldap-slave slapd-ldap-slave-unibs[914]: conn=3961 op=25098 SRCH base="ou=utenti,o=unibs,dc=unibs,dc=it" scope=2 deref=0 filter="(&(mail=*@student
Jul 25 08:34:17 ldap-slave slapd-ldap-slave-unibs[914]: conn=3961 op=25098 SRCH attr=radiusNASIpAddress radiusExpiration acctFlags userPassword dBCSPwd sambaNtPa
Jul 25 08:34:17 ldap-slave slapd-ldap-slave-unibs[914]: conn=3961 op=25098 SEARCH RESULT tag=101 err=0 nentries=1 text=
Jul 25 08:34:17 ldap-slave slapd-ldap-slave-unibs[914]: conn=3961 op=25099 SRCH base="ou=utenti,o=unibs,dc=unibs,dc=it" scope=2 deref=0 filter="(&(mail=*@student
Jul 25 08:34:17 ldap-slave slapd-ldap-slave-unibs[914]: conn=3961 op=25099 SRCH attr=radiusNASIpAddress radiusExpiration acctFlags userPassword dBCSPwd sambaNtPa
Jul 25 08:34:17 ldap-slave slapd-ldap-slave-unibs[914]: conn=3961 op=25099 SEARCH RESULT tag=101 err=0 nentries=1 text=

systemctl list-units -t service | grep slapd
slapd-ldap-slave-unibs.service     loaded active running LSB: OpenLDAP

**Comment by davidcoutadeur** [comment]
The startup script must not be renamed while upgrading, because some installation postscripts are doing verifications involving status or restart actions.
So for me it is not a bug.

I propose the following:
1. rename the systemctl script as "slapd"
2. upgrade
3. rename the systemctl script as its previous name

Can you test and tell me if it is ok for you?

**Comment by bv-unibs** [comment]
Hi,
I did what you mentioned: 

renamed the /etc/init.d/slapd-ldap-slave-unibs into slapd and then try to upgrade the errors keep occuring, here the results:

ddgroup: The group `ldap' already exists as a system group. Exiting.
Job for slapd.service failed. See 'systemctl status slapd.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript slapd, action "start" failed.
dpkg: error processing package openldap-ltb (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of openldap-ltb-check-password:
 openldap-ltb-check-password depends on openldap-ltb; however:
  Package openldap-ltb is not configured yet.

dpkg: error processing package openldap-ltb-check-password (--configure):
 dependency problems - leaving unconfigured
Processing triggers for systemd (215-17+deb8u7) ...
Errors were encountered while processing:
 openldap-ltb
 openldap-ltb-check-password
E: Sub-process /usr/bin/dpkg returned an error code (1)

Now i reverted the machine to the previous status, because it's a production server and we cannot afford   to keep the service down for a long time..

regards

**Comment by davidcoutadeur** [comment]
Ok.
When appropriate, you can check why there is a problem with the startup script

1. rename the init script as "slapd"
2. test "status", "stop" and "start" targets
3. rename the init script as its previous name

**Comment by bv-unibs** [comment]
Hi, we managed to solve the problem, simply stopping the openldap service, and the running the upgrade..

everything wents fine..

thanks for your help

Regards

**Comment by davidcoutadeur** [comment]
Ok, good for you.
