### ISSUE TITLE
postinst doesn't follow policy-rc.d

### ISSUE THREAD

**Issue by tchernomax** [ltb-project/openldap-deb#78]
On debian policy-rc.d allow to declare if a package should start at install or not:
https://manpages.debian.org/experimental/policy-rcd-declarative/policy-rc.d-declarative.8.en.html

In postinst script `systemctl start slapd` is used ; so this policy  can't be taken into account.

You should use `invoke-rc.d slapd start` instead (invoke-rc.d will call systemctl by himself).

Thanks

**Comment by davidcoutadeur** [comment]
Thanks Maxime for your report and your contribution!

I have just merged it into `openldap24` branch, and I have also integrated it into `openldap25` branch
