### ISSUE TITLE
add debian stretch

### ISSUE THREAD

**Issue by laodc** [ltb-project/openldap-deb#8]
as topic states

**Comment by coudot** [comment]
Did you try to install the jessie version on stretch?

**Comment by davidcoutadeur** [comment]
libslp1 is no more present in stretch, but was an openldap-ltb dependency.
Need to check if this package is really necessary.

**Comment by davidcoutadeur** [comment]
libslp was a debian slapd package dependency.
It has never been compiled with openldap-ltb (./configure --enable-slp) and can now be removed safely.
--> libslp dependency should be removed in every openldap-ltb package. (will be for next OpenLDAP release 2.4.46 ?)

**Comment by coudot** [comment]
We can indeed wait for 2.4.46 unless we have some users blocked by this dependency, in this case we could ship new 2.4.45 Debian packages.

**Comment by davidcoutadeur** [comment]
Yep, this is a blocking issue for stretch package, as libslp has been removed in this version of debian.

**Comment by davidcoutadeur** [comment]
@coudot  I am planning to package for debian stretch soon, so you can integrate this new package in the repo

**Comment by davidcoutadeur** [comment]
Modifications done in 33ace7d

**Comment by coudot** [comment]
Great, I will create the repo for stretch

**Comment by coudot** [comment]
Packages are published here: https://ltb-project.org/debian/stretch/

@davidcoutadeur, we also need berkerydb-ltb package here, can we use the jessie one or do we need to repackage it?

**Comment by davidcoutadeur** [comment]
@coudot I don't know if using the jessie one would work. But as I had recompiled it anyway, you can just use the latter.

**Comment by coudot** [comment]
Thanks! Package is now on the repository. I think you can close this issue.

**Comment by davidcoutadeur** [comment]
I will close as soon as I have automated the stretch packaging

**Comment by davidcoutadeur** [comment]
Done
